[package]
name = "sqlite-parquet"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlite-loadable = "0.0.5"
parquet = {version="24.0.0", features=["json"]}
chrono = "0.4"
serde_json = "1.0.87"

[lib]
crate-type=["lib", "cdylib", "staticlib"]